### ISSUE TITLE
Won't work if level is Multimedia

### ISSUE THREAD

**Issue by alidouiyek** [raineorshine/memrise-export#3]
Hi, 
The extension is unable to generate a list if a course has a Multimedia (not words) level. For example in [**this course**](https://app.memrise.com/course/983/hsk-level-3/)

The same problem happens with the [**script** ](https://gist.github.com/raineorshine/68fab3b4b96f54b808a858217b83fe94) version that you provided. But in the script we can specify at which level we should start collecting data and that seems to fix the issue.
For more complex courses like [**this**](https://app.memrise.com/course/127/1-videos-watch-to-learn-300-phrases/) which alternates between multimedia levels and word levels that workaround doesn't work.

**Comment by raineorshine** [comment]
Thanks for reporting! I believe I fixed it. Just waiting for the Chrome Store to update.

If you'd like to test it immediately, you can download the repo and load it as an unpacked extension as described in the [README](https://github.com/raineorshine/memrise-export#install-manually) or in this [StackOverflow answer](https://stackoverflow.com/a/24577660/480608). Would love to know if it's working for you.

**Comment by alidouiyek** [comment]
I just checked, problem fixed.
That was quick !  
Thank you !
